import './globals.css';
import '@blocknote/core/fonts/inter.css';
import '@blocknote/mantine/style.css';
import '@liveblocks/react-ui/styles.css';
import '@liveblocks/react-ui/styles/dark/media-query.css';
import '@liveblocks/react-tiptap/styles.css';

import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'SyncSpace',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
